-- Baseline schema for the PostgreSQL profile (stg/prod).
--
-- This file is the "version 1" migration: docker-compose mounts it into the
-- postgres container's entrypoint so a local database comes up ready, and it is
-- the script you carry into a real environment. It matches the JPA entities, so
-- `spring.jpa.hibernate.ddl-auto=validate` (prod) passes against it. Add later
-- changes as new, ordered migration files rather than editing this one.
--
-- No user rows are seeded here on purpose: the admin bootstrap user is created by
-- DataInitialization with its password hashed through the application's
-- PasswordEncoder (enable it with APP_INIT_ADD_ADMIN=true). Never store plaintext
-- or hand-written password hashes in SQL.

CREATE TABLE IF NOT EXISTS users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    subscription_plan VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    roles   VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles (user_id);
